### ISSUE TITLE
mapping the characters

### ISSUE THREAD

**Issue by AntonioDEM** [YiNNx/typora-theme-lapis#26]
I find this theme very interesting, but I have serious problems in mapping the characters in Italian and Spanish

![Scr 2023-06-03 alle 08 34 58](https://github.com/YiNNx/typora-theme-lapis/assets/18247765/e4c7d88a-8e95-495d-87ae-a9227176ca5c)

**Comment by YiNNx** [comment]
Thanks for your issue! This is most likely caused by the font file rendering incompatibility in MacOS. 
You can simply comment or delete the following code in `lapis.css` to ensure normal display, though the font style will be lost. 
```css
@font-face {
  font-family: "Cantarell";
  src: url('lapis/Cantarell-VF.otf');
}
```
Or you can clone the latest code of the master branch. I tried to fix this problem in PR #22 by replacing the font file with `Cantarell-VF-new.otf`, but it has not been updated to the download link. If you can help to confirm whether the replaced font  can be displayed normally, it would be even more grateful.

**Comment by AntonioDEM** [comment]
I haven't solved the problem. I think the defect is in the **SourceHanSerifCN-Bold.otf** fonts that are not read by the mac. I disabled what you suggested, I also installed all the fonts in the system and did several tests, it doesn't work.

the problem is that the font "SourceHanSerifCN-Bold.ttf" doesn't exist?

i also have problems inside the text for the bold character ** ** always with the letters T , t, p

Could you try inserting alternative characters? I really like the kind of setup you use


![Scr 2023-06-12 alle 08 23 33](https://github.com/YiNNx/typora-theme-lapis/assets/18247765/d9b07e43-56ad-4f69-b314-c9b40a570be1)

**Comment by YiNNx** [comment]
This is a display problem of some system versions of macOS, and it also exists for English, but I can't reproduce it... Maybe this theme's fonts needs to be replaced with ones that are more suitable for display on macOS and for multiple languages.

I will change the font in the subsequent Release to ensure the normal display of multiple languages. 
In order to temporarily display normally, you can re-download [Release](https://github.com/YiNNx/typora-theme-lapis/releases/tag/v1.0.0), search and delete the following two lines of code in `lapis.css`, many people said that this can solve the problem.

```css
    font-family: 'Cantarell', 'SourceHanSerifCN';
```

```css
    font-family: 'Cantarell', 'SourceHanSerifCN', 'JetBrainsMono';
```

**Comment by AntonioDEM** [comment]
yes, deleting the two lines solves the problem. it would be interesting to be able to find similar but more readable fonts

**Comment by YiNNx** [comment]
@AntonioDEM Hi, a few days ago I [opened an issue](https://gitlab.gnome.org/GNOME/cantarell-fonts/-/issues/69) to the Cantarell official repositery to figure out the reason of the font display problem. According to their reply, building the font file without `ps-autohinting` may fix it.
[Cantarell-VF-fixed.zip](https://github.com/YiNNx/typora-theme-lapis/files/12063562/Cantarell-VF-fixed.zip)
Could you help to check if this works? Just download the file above, double-click to open the font review, and see if all characters can be displayed properly.

**Comment by AntonioDEM** [comment]
@YiNNx hi. Ok in this days i check the files. Tnks
